version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Stripe.net
    versions:
    - ">= 39.7.a, < 39.8"
  - dependency-name: FluentValidation
    versions:
    - 10.0.2
    - 10.0.3
    - 9.5.1
    - 9.5.2
    - 9.5.3
  - dependency-name: YamlDotNet
    versions:
    - 10.0.0
    - 11.0.1
    - 11.1.1
    - 9.1.4
  - dependency-name: Microsoft.AspNetCore.Mvc.Testing
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
    - 5.0.5
  - dependency-name: Stripe.net
    versions:
    - 39.33.0
    - 39.34.0
    - 39.35.0
    - 39.37.0
    - 39.38.0
    - 39.39.0
    - 39.41.0
    - 39.43.0
  - dependency-name: Foundatio.Redis
    versions:
    - 10.0.2
  - dependency-name: Foundatio.Extensions.Hosting
    versions:
    - 10.0.2
  - dependency-name: AsyncFixer
    versions:
    - 1.5.1
  - dependency-name: Foundatio.AzureStorage
    versions:
    - 10.0.2
  - dependency-name: Foundatio.RabbitMQ
    versions:
    - 10.0.2
  - dependency-name: Foundatio.AWS
    versions:
    - 10.0.2
  - dependency-name: Foundatio.Repositories.Elasticsearch
    versions:
    - 7.10.3
    - 7.10.4
    - 7.10.5
  - dependency-name: Microsoft.Extensions.Diagnostics.HealthChecks
    versions:
    - 5.0.2
  - dependency-name: Microsoft.AspNetCore.Mvc.NewtonsoftJson
    versions:
    - 5.0.2
  - dependency-name: Handlebars.Net
    versions:
    - 2.0.4
  - dependency-name: Microsoft.Extensions.DependencyInjection
    versions:
    - 5.0.1
  - dependency-name: NEST.JsonNetSerializer
    versions:
    - 7.10.1
  - dependency-name: Serilog.Sinks.ExceptionLess
    versions:
    - 3.1.3
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
